version: 2.0

jobs:
  build:
    docker:
      - image: makenowjust/bashcached-circleci-test:latest

    steps:
      - checkout
      - run:
          name: Run shellcheck
          command: |
            shellcheck --version
            shellcheck bashcached
      - run:
          name: Run tests
          command: |
            ruby --version
            rake --version
            memcached -V
            TERM=xterm rake test TEST_MEMCACHED=1
            TERM=xterm rake test
